# Generated by Django 5.1.6 on 2025-02-12 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsModel',
            new_name='News',
        ),
    ]
