# Generated by Django 5.1.6 on 2025-02-12 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_newsmodel_news'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='NewsModel',
        ),
    ]
