# Generated by Django 5.1.6 on 2025-02-12 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_rename_news_newsmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsModel',
            new_name='News',
        ),
    ]
